
-- 3 years of sales report of a Electronic Store

--1.FIND THE TOP PRODUCTS WITH THE HIGHEST SALES GROWTH RATE OVER THE PREVIOUS MONTH

SELECT CMS.PRODUCT_NAME, CMS.SALES LATEST_SALE, CAST(((CMS.SALES - PMS.SALES)/PMS.SALES)*100 AS DECIMAL(10,2)) AS GROWTH_RATE_
FROM
	(
		SELECT  PRODUCT_NAME, SUM(SALES) SALES
		FROM COMP_SALES
		WHERE 
		MONTH(ORDER_DATE) = (SELECT MONTH(MAX(ORDER_DATE)) FROM COMP_SALES)
		AND
		YEAR(ORDER_DATE) = (SELECT YEAR(MAX(ORDER_DATE)) FROM COMP_SALES)
		GROUP BY PRODUCT_NAME
	)  CMS
	JOIN
	(
		SELECT PRODUCT_NAME,SUM(SALES) SALES
		FROM COMP_SALES
		WHERE 
		MONTH(ORDER_DATE) = (SELECT MONTH(DATEADD(MONTH,-1,MAX(ORDER_DATE))) FROM COMP_SALES)
		AND 
		YEAR(ORDER_DATE) = (SELECT YEAR(DATEADD(MONTH,-1,MAX(ORDER_DATE))) FROM COMP_SALES)
		GROUP BY PRODUCT_NAME
	)  PMS
	ON  CMS.PRODUCT_NAME =  PMS.PRODUCT_NAME


--2. FIND THE CUSTOMERS WHO HAVE PLACED ORDERS IN MULTIPLE COUNTRIES AND THE NUMBER OF COUNTRIES THEY HAVE ORDERED IN:

SELECT COUNTRY, COUNT(COUNTRY) NO_OF_ORDERS
FROM COMP_SALES
GROUP BY COUNTRY

--3 FIND THE AVERAGE SALES PER ORDER FOR EACH PRODUCT CATEGORY IN EACH REGION:
SELECT * FROM COMP_SALES

SELECT REGION, PRODUCT_CATEGORY, AVG(SALES/ORDER_QTY) AVERAGE_SALES_PERORDER
FROM
	COMP_SALES
GROUP BY REGION, PRODUCT_CATEGORY

--4 FIND THE PRODUCTS WITH THE HIGHEST SALES IN EACH PRODUCT SUB-CATEGORY AND THE PERCENTAGE OF TOTAL SALES THEY REPRESENT:

SELECT * FROM COMP_SALES ORDER BY SALES DESC

--++++++++++++++++ USING SUB QUERY ++++++++++++++++++++++++++
SELECT PRODUCT_NAME, PRODUCT_SUB_CATEGORY, SALES
FROM COMP_SALES A
WHERE SALES =	(
					SELECT MAX(SALES)
					FROM COMP_SALES B
					WHERE A.PRODUCT_SUB_CATEGORY = B.PRODUCT_SUB_CATEGORY
				)
ORDER BY SALES DESC


--++++++++++++++++ USING JOIN ++++++++++++++++++++++++++
SELECT A.PRODUCT_NAME,A.PRODUCT_SUB_CATEGORY,A.SALES
FROM COMP_SALES A
JOIN
(
	SELECT PRODUCT_SUB_CATEGORY,MAX(SALES) MAX_SALES
	FROM COMP_SALES
	GROUP BY PRODUCT_SUB_CATEGORY
) B
ON A.PRODUCT_SUB_CATEGORY = B.PRODUCT_SUB_CATEGORY AND A.SALES = B.MAX_SALES


--FIND THE CATEGORY WHO GOT ORDERS IN EVERY MONTH OF THE CURRENT YEAR:

WITH SALES_MONTH AS
(
	SELECT COUNT(MONTH(ORDER_DATE)) AS ORDER_MONTHS, PRODUCT_NAME, PRODUCT_CATEGORY
	FROM COMP_SALES
	GROUP BY PRODUCT_NAME, PRODUCT_CATEGORY
)

SELECT PRODUCT_NAME, PRODUCT_CATEGORY
FROM SALES_MONTH
WHERE ORDER_MONTHS = 12
GROUP BY PRODUCT_NAME, PRODUCT_CATEGORY


--FIND THE PRODUCTS WITH THE HIGHEST PROFIT MARGIN IN EACH PRODUCT CATEGORY:

SELECT * FROM COMP_SALES

SELECT B.PRODUCT_NAME, A.PRODUCT_CATEGORY,A.PROFIT_MARGIN
FROM
	(
		SELECT PRODUCT_CATEGORY, MAX(PROFIT) PROFIT_MARGIN
		FROM
			COMP_SALES
		GROUP BY 
			PRODUCT_CATEGORY
	) A
	JOIN
	(
		SELECT *
		FROM
			COMP_SALES
	) B
	ON
	A.PRODUCT_CATEGORY = B.PRODUCT_CATEGORY AND A.PROFIT_MARGIN = B.PROFIT

--FIND THE COUNTRIES WITH THE HIGHEST SALES GROWTH RATE FOR THE LAST QUARTER.
SELECT* FROM COMP_SALES ORDER BY ORDER_DATE DESC	

WITH TOTAL_SALES
AS
(
SELECT 
		YEAR(ORDER_DATE) AS YEARS
	   , COUNTRY
		, DATEPART(QUARTER, ORDER_DATE) AS QUARTERS
		, SUM(SALES) QTR_SALES
		,LAG(SUM(SALES)) OVER (PARTITION BY COUNTRY ORDER BY YEAR(ORDER_DATE), COUNTRY, DATEPART(QUARTER, ORDER_DATE)) PREVIOUS_QTR
	FROM
		COMP_SALES
	GROUP BY
		YEAR(ORDER_DATE)
		, COUNTRY
		, DATEPART(QUARTER, ORDER_DATE)
		
	
)
SELECT	TOP 5 *
		, CAST(100*((QTR_SALES-PREVIOUS_QTR)/PREVIOUS_QTR) AS DECIMAL(10,2)) AS GROWTH_RATE
FROM TOTAL_SALES
WHERE QUARTERS = 4
ORDER BY GROWTH_RATE DESC


-- CALCULATE THE CUMULATIVE SALES FOR EACH PRODUCT WITHIN A SUBCATEGORY, ORDERED BY DATE:


SELECT * FROM COMP_SALES


SELECT	PRODUCT_NAME, PRODUCT_SUB_CATEGORY
		, SUM(SALES) OVER (PARTITION BY PRODUCT_SUB_CATEGORY ORDER BY ORDER_DATE ) CUMMULATIVE_SALES
		, SALES
FROM
	COMP_SALES



-- FIND THE PRODUCT_NAME WHO HAVE MADE PURCHASES IN ALL REGIONS:

--SELECT * FROM COMP_SALES

SELECT	PRODUCT_NAME,
		COUNT(DISTINCT REGION) TOTAL_REGION
FROM
	COMP_SALES
GROUP BY 
	PRODUCT_NAME
HAVING
	COUNT(DISTINCT REGION) = (SELECT COUNT(DISTINCT REGION) FROM COMP_SALES)

--CALCULATE THE AVERAGE SALES GROWTH RATE FOR EACH COMPANY, COMPARING THE TOTAL REVENUE BETWEEN THE CURRENT YEAR AND THE PREVIOUS YEAR:

--SELECT * FROM COMP_SALES

SELECT T1.MANUFACTURER, T1.TOTALREVENUE, T2.TOTALREVENUE,((T1.TOTALREVENUE - T2.TOTALREVENUE) / T2.TOTALREVENUE) * 100 AS SALESGROWTHRATE
FROM (
    SELECT MANUFACTURER, SUM(SALES) AS TOTALREVENUE
    FROM COMP_SALES
    WHERE DATEPART(YEAR, ORDER_DATE) = 2019 -- REPLACE WITH THE DESIRED YEAR
    GROUP BY MANUFACTURER
) T1
JOIN (
    SELECT MANUFACTURER, SUM(SALES) AS TOTALREVENUE
    FROM COMP_SALES
    WHERE DATEPART(YEAR, ORDER_DATE) = 2018 -- REPLACE WITH THE DESIRED PREVIOUS YEAR
    GROUP BY MANUFACTURER
) T2 ON T1.MANUFACTURER = T2.MANUFACTURER;




